# Generated by Django 4.2.1 on 2023-05-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerrAttebdance',
            new_name='EmployerrAttendance',
        ),
    ]
