# Generated by Django 4.2.1 on 2023-05-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_employerrattebdance_employerrattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerrAttendance',
            new_name='EmployeeAttendance',
        ),
    ]
